version: 2
updates:
  - package-ecosystem: "npm"
    directory: "."
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
        exclude-patterns:
          - "typescript"
          - "zone.js"
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    groups:
      gha:
        patterns:
          - "*"
